apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-auto-healing
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/k8s-auto-healing.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
