apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-config
  labels:
    grafana_dashboard: "1"
data:
  k8s-auto-healing-dashboard.json: |
    {
      "apiVersion": 1,
      "providers": [
        {
          "name": "Kubernetes Auto-Healing",
          "orgId": 1,
          "folder": "",
          "type": "file",
          "disableDeletion": false,
          "editable": true,
          "options": {
            "path": "/var/lib/grafana/dashboards"
          }
        }
      ]
    }

