apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-auto-healing-prometheus
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: k8s-auto-healing
  endpoints:
  - port: http
    path: /metrics
    interval: 15s

