name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |  
        docker build -f src/Dockerfile -t ghcr.io/your-username/k8s-auto-healing:latest .

    - name: Update Kubernetes Manifests
      run: |
        sed -i 's|image:.*|image: ghcr.io/your-username/k8s-auto-healing:latest|' manifests/deployment.yaml
        git commit -am "Updated image to latest version"
        git push

    - name: Sync with ArgoCD
      run: |
        argocd app sync my-app

