name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write  # Allows pushing to GHCR.io

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git user identity
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Install ArgoCD CLI
      run: |
        curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x argocd-linux-amd64
        sudo mv argocd-linux-amd64 /usr/local/bin/argocd
        argocd version --client

    - name: Log in to GitHub Container Registry (GHCR) using GITHUB_TOKEN
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -f src/Dockerfile -t ghcr.io/${{ github.actor }}/k8s-auto-healing:latest .
        docker images | grep k8s-auto-healing  # Verify the image exists
        docker push ghcr.io/${{ github.actor }}/k8s-auto-healing:latest

    - name: Update Kubernetes Manifests
      run: |
        sed -i 's|image:.*|image: ghcr.io/${{ github.actor }}/k8s-auto-healing:latest|' manifests/deployment.yaml
        git add manifests/deployment.yaml
        git commit -m "Updated image to latest version"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

    - name: Sync with ArgoCD
      run: |
        argocd app sync my-app
