name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git user identity
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Build Docker image
      run: |
        docker build -f src/Dockerfile -t ghcr.io/your-username/k8s-auto-healing:latest .
        docker push ghcr.io/your-username/k8s-auto-healing:latest

    - name: Update Kubernetes Manifests
      run: |
        sed -i 's|image:.*|image: ghcr.io/your-username/k8s-auto-healing:latest|' manifests/deployment.yaml
        git add manifests/deployment.yaml
        git commit -m "Updated image to latest version"
        git push

    - name: Sync with ArgoCD
      run: |
        argocd app sync my-app

